// WBS Datos SICC v6.3 - DBCI DETERMINISTA
window.wbsDataPresupuestal = [
    {
        "item": "1.1.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Servidores CTC principales",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 180000000,
        "total": 360000000,
        "vu_usd": 45000,
        "total_usd": 90000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Servidores CTC respaldo",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 180000000,
        "total": 360000000,
        "vu_usd": 45000,
        "total_usd": 90000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Workstations operadores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "8",
        "vu": 45000000,
        "total": 360000000,
        "vu_usd": 11250,
        "total_usd": 90000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.103",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Software CTC virtual + Autorizaciones PTC + Interoperabilidad FENOCO",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 88112090432,
        "total": 88112090432,
        "vu_usd": 22028023,
        "total_usd": 22028023,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.104",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Base de datos centralizada",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 200000000,
        "total": 200000000,
        "vu_usd": 50000,
        "total_usd": 50000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.105",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Sistema redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 300000000,
        "total": 300000000,
        "vu_usd": 75000,
        "total_usd": 75000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.106",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Interfaces comunicaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 37500,
        "total_usd": 37500,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Computadora PTC embarcada",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 120000000,
        "total": 1800000000,
        "vu_usd": 30000,
        "total_usd": 450000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Display maquinista",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 80000000,
        "total": 1200000000,
        "vu_usd": 20000,
        "total_usd": 300000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Sensores velocidad",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 25000000,
        "total": 375000000,
        "vu_usd": 6250,
        "total_usd": 93750,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.103",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Sistema GPS",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 35000000,
        "total": 525000000,
        "vu_usd": 8750,
        "total_usd": 131250,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.104",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Software PTC",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 100000000,
        "total": 1500000000,
        "vu_usd": 25000,
        "total_usd": 375000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.105",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Interfaces frenos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 30000000,
        "total": 450000000,
        "vu_usd": 7500,
        "total_usd": 112500,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.106",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Sistema redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 50000000,
        "total": 750000000,
        "vu_usd": 12500,
        "total_usd": 187500,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE Zapatosa",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 800000000,
        "total": 800000000,
        "vu_usd": 200000,
        "total_usd": 200000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE Garc\u00eda Cadena",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 800000000,
        "total": 800000000,
        "vu_usd": 200000,
        "total_usd": 200000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE Barrancabermeja",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 800000000,
        "total": 800000000,
        "vu_usd": 200000,
        "total_usd": 200000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.103",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE Puerto Berr\u00edo-Grecia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 800000000,
        "total": 800000000,
        "vu_usd": 200000,
        "total_usd": 200000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.104",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE La Dorada-M\u00e9xico",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 800000000,
        "total": 800000000,
        "vu_usd": 200000,
        "total_usd": 200000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.105",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Sistema redundancia ENCE",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 400000000,
        "total": 400000000,
        "vu_usd": 100000,
        "total_usd": 100000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.106",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Interfaces CTC-ENCE",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "5",
        "vu": 60000000,
        "total": 300000000,
        "vu_usd": 15000,
        "total_usd": 75000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.4.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.4",
        "descripcion": "Desv\u00edos motorizados CTC",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "25",
        "vu": 448589000,
        "total": 11214725000,
        "vu_usd": 112147,
        "total_usd": 2803681,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.4.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.4",
        "descripcion": "Sistemas control remoto + redundancia N+1",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "25",
        "vu": 134577000,
        "total": 3364425000,
        "vu_usd": 33644,
        "total_usd": 841106,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.4.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.4",
        "descripcion": "Interfaces CTC/ENCE",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "25",
        "vu": 67288000,
        "total": 1682200000,
        "vu_usd": 16822,
        "total_usd": 420550,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.5.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.5",
        "descripcion": "Desv\u00edos manuales autotalonables (con comprobador integrado)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "120",
        "vu": 134577000,
        "total": 16149240000,
        "vu_usd": 33644,
        "total_usd": 4037310,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.5.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.5",
        "descripcion": "Se\u00f1alizaci\u00f3n luminosa estaciones ENCE (entrada/salida)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "10",
        "vu": 10000000,
        "total": 100000000,
        "vu_usd": 2500,
        "total_usd": 25000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.5.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.5",
        "descripcion": "Herramientas operaci\u00f3n (kit completo certificado)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "120",
        "vu": 13458000,
        "total": 1614960000,
        "vu_usd": 3365,
        "total_usd": 403740,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.100",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Torres autosoportadas",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 180000000,
        "total": 6660000000,
        "vu_usd": 45000,
        "total_usd": 1665000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.101",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Estaciones base TETRA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 65000000,
        "total": 2405000000,
        "vu_usd": 16250,
        "total_usd": 601250,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.102",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Antenas TETRA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 12000000,
        "total": 444000000,
        "vu_usd": 3000,
        "total_usd": 111000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.103",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Radios embarcados (30 unidades)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 35000000,
        "total": 1050000000,
        "vu_usd": 8750,
        "total_usd": 262500,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.104",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Radios port\u00e1tiles",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "80",
        "vu": 6000000,
        "total": 480000000,
        "vu_usd": 1500,
        "total_usd": 120000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.105",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Sistema control centralizado",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 120000000,
        "total": 120000000,
        "vu_usd": 30000,
        "total_usd": 30000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.106",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Casetas t\u00e9cnicas",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 65000000,
        "total": 2405000000,
        "vu_usd": 16250,
        "total_usd": 601250,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.107",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Cimentaciones",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 25000000,
        "total": 925000000,
        "vu_usd": 6250,
        "total_usd": 231250,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.108",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Cerramiento perimetral",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 30000000,
        "total": 1110000000,
        "vu_usd": 7500,
        "total_usd": 277500,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.109",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "V\u00edas de acceso",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 25000000,
        "total": 925000000,
        "vu_usd": 6250,
        "total_usd": 231250,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.110",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Sistemas de seguridad",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 20000000,
        "total": 740000000,
        "vu_usd": 5000,
        "total_usd": 185000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.111",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Montaje e instalaci\u00f3n",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 15000000,
        "total": 555000000,
        "vu_usd": 3750,
        "total_usd": 138750,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.112",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Configuraci\u00f3n red",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 200000000,
        "total": 200000000,
        "vu_usd": 50000,
        "total_usd": 50000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.113",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Pruebas cobertura",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 37500,
        "total_usd": 37500,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.114",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Capacitaci\u00f3n",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 25000,
        "total_usd": 25000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.115",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 0,
        "total": 1774000000,
        "vu_usd": 0,
        "total_usd": 443500,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.100",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Estaciones base RED TETRA (Misi\u00f3n Cr\u00edtica)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 45000000,
        "total": 1665000000,
        "vu_usd": 11250,
        "total_usd": 416250,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.101",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Antenas RED TETRA (Misi\u00f3n Cr\u00edtica)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 8000000,
        "total": 296000000,
        "vu_usd": 2000,
        "total_usd": 74000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.102",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Radios embarcados RED TETRA (Misi\u00f3n Cr\u00edtica)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 25000000,
        "total": 750000000,
        "vu_usd": 6250,
        "total_usd": 187500,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.103",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Sistema control RED TETRA (Misi\u00f3n Cr\u00edtica)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 20000,
        "total_usd": 20000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.104",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Interfaces TETRA-RED TETRA (Misi\u00f3n Cr\u00edtica)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 5000000,
        "total": 185000000,
        "vu_usd": 1250,
        "total_usd": 46250,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.105",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Sistema redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 37500,
        "total_usd": 37500,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.106",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Configuraci\u00f3n dual",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 25000,
        "total_usd": 25000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.107",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Pruebas integraci\u00f3n",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 20000,
        "total_usd": 20000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.108",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 0,
        "total": 312000000,
        "vu_usd": 0,
        "total_usd": 78000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.100",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "Cable fibra \u00f3ptica 48 fibras (Instalaci\u00f3n 526km + 10% Gasa T\u00e9cnica)",
        "tipo": "SUMINISTRO",
        "unidad": "KM",
        "cantidad": "579",
        "vu": 9811013,
        "total": 5680576527,
        "vu_usd": 2453,
        "total_usd": 1420144,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.101",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "Mano de obra instalaci\u00f3n (Tendido 526km + 10% Gasa T\u00e9cnica)",
        "tipo": "OBRA",
        "unidad": "KM",
        "cantidad": "579",
        "vu": 90188987,
        "total": 52219423473,
        "vu_usd": 22547,
        "total_usd": 13054856,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.102",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "Tritubo 40mm",
        "tipo": "SUMINISTRO",
        "unidad": "ROLLO",
        "cantidad": "1448",
        "vu": 15845,
        "total": 22943560,
        "vu_usd": 4,
        "total_usd": 5736,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.103",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "Cajas empalme 80x80",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1930",
        "vu": 1350000,
        "total": 2605500000,
        "vu_usd": 338,
        "total_usd": 651375,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.104",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "Uniones r\u00e1pidas",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "5790",
        "vu": 35000,
        "total": 202650000,
        "vu_usd": 9,
        "total_usd": 50663,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.105",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "Fusionadoras",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 50000000,
        "total": 100000000,
        "vu_usd": 12500,
        "total_usd": 25000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.106",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "OTDR",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 30000000,
        "total": 60000000,
        "vu_usd": 7500,
        "total_usd": 15000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.107",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "Muflas fusionado",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "6800",
        "vu": 25000,
        "total": 170000000,
        "vu_usd": 6,
        "total_usd": 42500,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.108",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "Insumos fusionado",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "6200",
        "vu": 15000,
        "total": 93000000,
        "vu_usd": 4,
        "total_usd": 23250,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.109",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.3",
        "descripcion": "Repuestos Estrat\u00e9gicos (Stock 3% Corredor)",
        "tipo": "SUMINISTRO",
        "unidad": "KM",
        "cantidad": "16",
        "vu": 8000000,
        "total": 128000000,
        "vu_usd": 2000,
        "total_usd": 32000,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.100",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "C\u00e1maras PAN PTZ 4MP (73 unidades - cobertura completa)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "73",
        "vu": 30000000,
        "total": 2190000000,
        "vu_usd": 7500,
        "total_usd": 547500,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.101",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "C\u00e1maras talleres (12 unidades)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "12",
        "vu": 6000000,
        "total": 72000000,
        "vu_usd": 1500,
        "total_usd": 18000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.102",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "C\u00e1maras CCO (8 unidades)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "8",
        "vu": 10000000,
        "total": 80000000,
        "vu_usd": 2500,
        "total_usd": 20000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.103",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "C\u00e1maras estaciones (5 unidades)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "5",
        "vu": 7000000,
        "total": 35000000,
        "vu_usd": 1750,
        "total_usd": 8750,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.104",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Sistema grabaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 37500,
        "total_usd": 37500,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.105",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Servidores almacenamiento",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 80000000,
        "total": 160000000,
        "vu_usd": 20000,
        "total_usd": 40000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.106",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Software an\u00e1lisis",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 120000000,
        "total": 120000000,
        "vu_usd": 30000,
        "total_usd": 30000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.107",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Monitores CCO",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "8",
        "vu": 15000000,
        "total": 120000000,
        "vu_usd": 3750,
        "total_usd": 30000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.108",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Instalaci\u00f3n y configuraci\u00f3n",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "73",
        "vu": 2000000,
        "total": 146000000,
        "vu_usd": 500,
        "total_usd": 36500,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.109",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 0,
        "total": 307300000,
        "vu_usd": 0,
        "total_usd": 76825,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.100",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Lectores RFID control accesos (ISO 14443, IP65/IK10)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "100",
        "vu": 3000000,
        "total": 300000000,
        "vu_usd": 750,
        "total_usd": 75000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.101",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Tarjetas RFID",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1000",
        "vu": 25000,
        "total": 25000000,
        "vu_usd": 6,
        "total_usd": 6250,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.102",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Sistema biom\u00e9trico",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "5",
        "vu": 50000000,
        "total": 250000000,
        "vu_usd": 12500,
        "total_usd": 62500,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.103",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Software control accesos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 20000,
        "total_usd": 20000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.104",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Cerraduras electr\u00f3nicas",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "50",
        "vu": 8000000,
        "total": 400000000,
        "vu_usd": 2000,
        "total_usd": 100000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.105",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Intercomunicadores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "20",
        "vu": 15000000,
        "total": 300000000,
        "vu_usd": 3750,
        "total_usd": 75000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.106",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Instalaci\u00f3n y configuraci\u00f3n",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 25000,
        "total_usd": 25000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.107",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 0,
        "total": 145500000,
        "vu_usd": 0,
        "total_usd": 36375,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.100",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Detectores humo",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "200",
        "vu": 150000,
        "total": 30000000,
        "vu_usd": 38,
        "total_usd": 7500,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.101",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Detectores temperatura",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "150",
        "vu": 200000,
        "total": 30000000,
        "vu_usd": 50,
        "total_usd": 7500,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.102",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Sistema aspersores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "50",
        "vu": 800000,
        "total": 40000000,
        "vu_usd": 200,
        "total_usd": 10000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.103",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Extintores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "100",
        "vu": 500000,
        "total": 50000000,
        "vu_usd": 125,
        "total_usd": 12500,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.104",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Sistema alarma",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 120000000,
        "total": 120000000,
        "vu_usd": 30000,
        "total_usd": 30000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.105",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Botones emergencia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 500000,
        "total": 15000000,
        "vu_usd": 125,
        "total_usd": 3750,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.106",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Instalaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 20000,
        "total_usd": 20000,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.107",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 0,
        "total": 36500000,
        "vu_usd": 0,
        "total_usd": 9125,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.100",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Sistemas barreras autom\u00e1ticas",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 180000000,
        "total": 1620000000,
        "vu_usd": 45000,
        "total_usd": 405000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.101",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Se\u00f1alizaci\u00f3n LED",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 80000000,
        "total": 720000000,
        "vu_usd": 20000,
        "total_usd": 180000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.102",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Sistemas detecci\u00f3n veh\u00edculos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 360000000,
        "total": 3240000000,
        "vu_usd": 90000,
        "total_usd": 810000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.103",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Sistemas comunicaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 60000000,
        "total": 540000000,
        "vu_usd": 15000,
        "total_usd": 135000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.104",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Sistemas emergencia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 40000000,
        "total": 360000000,
        "vu_usd": 10000,
        "total_usd": 90000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.105",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Instalaci\u00f3n y configuraci\u00f3n",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 200000000,
        "total": 1800000000,
        "vu_usd": 50000,
        "total_usd": 450000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.106",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 0,
        "total": 828000000,
        "vu_usd": 0,
        "total_usd": 207000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.100",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Sistemas barreras manuales",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 120000000,
        "total": 1800000000,
        "vu_usd": 30000,
        "total_usd": 450000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.101",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Se\u00f1alizaci\u00f3n b\u00e1sica",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 50000000,
        "total": 750000000,
        "vu_usd": 12500,
        "total_usd": 187500,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.102",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Sistemas detecci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 80000000,
        "total": 1200000000,
        "vu_usd": 20000,
        "total_usd": 300000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.103",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Sistemas comunicaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 40000000,
        "total": 600000000,
        "vu_usd": 10000,
        "total_usd": 150000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.104",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Instalaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 60000000,
        "total": 900000000,
        "vu_usd": 15000,
        "total_usd": 225000,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.105",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 0,
        "total": 525000000,
        "vu_usd": 0,
        "total_usd": 131250,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.3.100",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.3",
        "descripcion": "Se\u00f1alizaci\u00f3n b\u00e1sica",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "122",
        "vu": 25000000,
        "total": 3050000000,
        "vu_usd": 6250,
        "total_usd": 762500,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.3.101",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.3",
        "descripcion": "Sistemas comunicaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "0",
        "vu": 20000000,
        "total": 0,
        "vu_usd": 5000,
        "total_usd": 0,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.3.102",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.3",
        "descripcion": "Instalaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "0",
        "vu": 30000000,
        "total": 0,
        "vu_usd": 7500,
        "total_usd": 0,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.3.103",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.3",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 0,
        "total": 305000000,
        "vu_usd": 0,
        "total_usd": 76250,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.100",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Construcci\u00f3n edificio",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 2500000000,
        "total": 2500000000,
        "vu_usd": 625000,
        "total_usd": 625000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.101",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sala de control",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 800000000,
        "total": 800000000,
        "vu_usd": 200000,
        "total_usd": 200000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.102",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sistemas HVAC",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 300000000,
        "total": 300000000,
        "vu_usd": 75000,
        "total_usd": 75000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.103",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sistemas el\u00e9ctricos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 400000000,
        "total": 400000000,
        "vu_usd": 100000,
        "total_usd": 100000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.104",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sistemas seguridad",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 200000000,
        "total": 200000000,
        "vu_usd": 50000,
        "total_usd": 50000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.105",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sistemas comunicaciones",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 37500,
        "total_usd": 37500,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.100",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Consolas operadores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "8",
        "vu": 120000000,
        "total": 960000000,
        "vu_usd": 30000,
        "total_usd": 240000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.101",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Pantallas de video",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "16",
        "vu": 25000000,
        "total": 400000000,
        "vu_usd": 6250,
        "total_usd": 100000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.102",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Sistema audio",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 20000,
        "total_usd": 20000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.103",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Sistema iluminaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 60000000,
        "total": 60000000,
        "vu_usd": 15000,
        "total_usd": 15000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.104",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Muebles y accesorios",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 25000,
        "total_usd": 25000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.100",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Servidores SCADA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 400000000,
        "total": 800000000,
        "vu_usd": 100000,
        "total_usd": 200000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.101",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Software SCADA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 5000000000,
        "total": 5000000000,
        "vu_usd": 1250000,
        "total_usd": 1250000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.102",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Base de datos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 37500,
        "total_usd": 37500,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.103",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Interfaces comunicaci\u00f3n",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 4112000000,
        "total": 4112000000,
        "vu_usd": 1028000,
        "total_usd": 1028000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.104",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Sistema redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 300000000,
        "total": 300000000,
        "vu_usd": 75000,
        "total_usd": 75000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.105",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Configuraci\u00f3n",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 25000,
        "total_usd": 25000,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.100",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Sistemas PTC embarcados",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 400000000,
        "total": 6000000000,
        "vu_usd": 100000,
        "total_usd": 1500000,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.101",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Radios TETRA embarcados",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 35000000,
        "total": 1050000000,
        "vu_usd": 8750,
        "total_usd": 262500,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.102",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Radios RED TETRA (Misi\u00f3n Cr\u00edtica) embarcados",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 25000000,
        "total": 750000000,
        "vu_usd": 6250,
        "total_usd": 187500,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.103",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Sistemas GPS",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 35000000,
        "total": 525000000,
        "vu_usd": 8750,
        "total_usd": 131250,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.104",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Sistemas redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 80000000,
        "total": 1200000000,
        "vu_usd": 20000,
        "total_usd": 300000,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.105",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Instalaci\u00f3n y configuraci\u00f3n",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 100000000,
        "total": 1500000000,
        "vu_usd": 25000,
        "total_usd": 375000,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.106",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 0,
        "total": 1102500000,
        "vu_usd": 0,
        "total_usd": 275625,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.2.100",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.2",
        "descripcion": "Dispositivos EOT completos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 25000000,
        "total": 375000000,
        "vu_usd": 6250,
        "total_usd": 93750,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.2.101",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.2",
        "descripcion": "Repuestos EOT (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 25000000,
        "total": 50000000,
        "vu_usd": 6250,
        "total_usd": 12500,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.2.102",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.2",
        "descripcion": "Instalaci\u00f3n EOT",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 5000000,
        "total": 75000000,
        "vu_usd": 1250,
        "total_usd": 18750,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.2.103",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.2",
        "descripcion": "Configuraci\u00f3n EOT",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 20000000,
        "total": 20000000,
        "vu_usd": 5000,
        "total_usd": 5000,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    }
];
