window.riesgosWbs = {
  "fecha_actualizacion": "2026-05-05",
  "riesgos": [
    {
      "items_wbs": [
        "1.1.100",
        "1.2.100"
      ],
      "fuente": "P42 / Docs SICC",
      "nivel_exposicion": "ALTA",
      "probabilidad_num": 0.7,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-AT3-01",
      "hito_verificacion": "H-SICC-001",
      "responsable": "Ing. Sistemas",
      "probabilidad": "Alta",
      "exposicion": 0.56,
      "plan_accion": "Alinear supuestos de diseño con PTC Nativo (49 CFR §236) y solicitar no-objeción a Interventoría sobre criterios V1 (AT1 Tabla 17)",
      "categoria": "Técnico",
      "origen_decision": "N/A",
      "descripcion": "Dependencia de definición final de protocolos PTC Nativo (FRA 49 CFR §236)",
      "estrategia": "Mitigar: PTC Nativo bajo 49 CFR §236.1005 (Virtual Fixed Block)"
    },
    {
      "items_wbs": [
        "1.1.106",
        "4.1.100"
      ],
      "fuente": "P42 / Interfaces",
      "nivel_exposicion": "BAJA",
      "probabilidad_num": 0.5,
      "impacto": "Bajo",
      "estado": "Activo",
      "impacto_num": 0.3,
      "id": "R-INT-01",
      "hito_verificacion": "H-INT-002",
      "responsable": "Comunicaciones",
      "probabilidad": "Media",
      "exposicion": 0.15,
      "plan_accion": "Coordinar reuniones operativas con FENOCO para validar protocolo Stop & Switch en Chiriguaná y handoff de tráfico",
      "categoria": "Técnico",
      "origen_decision": "N/A",
      "descripcion": "Coordinación operativa con FENOCO en interfaz Chiriguaná (Stop & Switch — sin integración técnica de protocolos)",
      "estrategia": "Mitigar: protocolo operativo Stop & Switch (AT1 Tabla 17, BCD §6)"
    },
    {
      "items_wbs": [],
      "fuente": "AT4 / P42",
      "nivel_exposicion": "MEDIA",
      "probabilidad_num": 0.5,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-AT4-01",
      "hito_verificacion": "Continuo",
      "responsable": "Ing. Sistemas",
      "probabilidad": "Media",
      "exposicion": 0.4,
      "plan_accion": "Realizar análisis RAMS detallado y asegurar redundancia N+1 en diseños críticos",
      "categoria": "Contractual",
      "origen_decision": "N/A",
      "descripcion": "Cumplimiento disponibilidad AT4",
      "estrategia": "Mitigar: N+1, monitoreo"
    },
    {
      "items_wbs": [],
      "fuente": "VII.2.11",
      "nivel_exposicion": "MEDIA",
      "probabilidad_num": 0.5,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-CYB-01",
      "hito_verificacion": "H-CYB-001",
      "responsable": "Ciberseguridad",
      "probabilidad": "Media",
      "exposicion": 0.4,
      "plan_accion": "Contratar póliza de seguro contra ciberriesgos y realizar auditorías de seguridad periódicas",
      "categoria": "Técnico",
      "origen_decision": "N/A",
      "descripcion": "Ciberseguridad IEC 62443",
      "estrategia": "Mitigar: Defensa en profundidad"
    },
    {
      "items_wbs": [
        "1.1.106",
        "5.3.103"
      ],
      "fuente": "41. Interfaces",
      "nivel_exposicion": "ALTA",
      "probabilidad_num": 0.7,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-IF-01",
      "hito_verificacion": "H-IF-003",
      "responsable": "PMO/Integración",
      "probabilidad": "Alta",
      "exposicion": 0.56,
      "plan_accion": "Realizar workshops de integración y definir ICD para cada par de sistemas",
      "categoria": "Gestión",
      "origen_decision": "N/A",
      "descripcion": "Desalineación en interfaces (ICD)",
      "estrategia": "Mitigar: Plan Gestión Interfaces"
    },
    {
      "items_wbs": [
        "1.0.100"
      ],
      "fuente": "40. Permisos",
      "nivel_exposicion": "MEDIA",
      "probabilidad_num": 0.5,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-PERM-01",
      "hito_verificacion": "H-PERM-001",
      "responsable": "Gestor Permisos",
      "probabilidad": "Media",
      "exposicion": 0.4,
      "plan_accion": "Iniciar gestión temprana de permisos y mantener comunicación constante con autoridad ambiental",
      "categoria": "Contractual",
      "origen_decision": "N/A",
      "descripcion": "Retrasos permisos ANE/ANLA",
      "estrategia": "Mitigar: Plan de permisos"
    },
    {
      "items_wbs": [
        "2.3.100",
        "2.3.103"
      ],
      "fuente": "DT-FIBRA-003",
      "nivel_exposicion": "CRÍTICA",
      "probabilidad_num": 0.7,
      "impacto": "Crítico",
      "estado": "Activo",
      "impacto_num": 1,
      "id": "R-FIBRA-001",
      "hito_verificacion": "Orden Mes -9",
      "responsable": "PMO Adquisiciones",
      "probabilidad": "Alta",
      "exposicion": 0.7,
      "plan_accion": "Ordenar fibra óptica con 9 meses de anticipación (Mes -9 respecto a instalación)",
      "categoria": "Cronograma",
      "origen_decision": "DT-FIBRA-003",
      "descripcion": "Lead time crítico fibra 9m (pago 3m + fabric 4m + nac 2m)",
      "estrategia": "EVITAR - Ordenar 9m antes"
    },
    {
      "items_wbs": [],
      "fuente": "Contrato",
      "nivel_exposicion": "MEDIA",
      "probabilidad_num": 0.5,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-FM-001",
      "hito_verificacion": "Continuo",
      "responsable": "PMO",
      "probabilidad": "Media",
      "exposicion": 0.4,
      "plan_accion": "Desarrollar plan de contingencia con proveedores alternativos y rutas de transporte backup",
      "categoria": "Fuerza Mayor",
      "origen_decision": "N/A",
      "descripcion": "Huelgas transporte, problemas FENOCO, paros sector",
      "estrategia": "MITIGAR - Plan contingencia, proveedores alternativos"
    },
    {
      "items_wbs": [],
      "fuente": "A.1 Análisis",
      "nivel_exposicion": "MEDIA",
      "probabilidad_num": 0.5,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-GES-004",
      "hito_verificacion": "H-APROB-M12",
      "responsable": "PMO",
      "probabilidad": "Media",
      "exposicion": 0.4,
      "plan_accion": "Crear y socializar matriz de aprobaciones con plazos claros para cada entregable",
      "categoria": "Gestión",
      "origen_decision": "N/A",
      "descripcion": "Desfase aprobación diseños vs cronograma Plan Obras",
      "estrategia": "MITIGAR - Integrar cronograma entregables ingeniería con Plan Obras"
    },
    {
      "items_wbs": [
        "3.2.100"
      ],
      "fuente": "A.2 Análisis",
      "nivel_exposicion": "MEDIA",
      "probabilidad_num": 0.5,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-CON-001",
      "hito_verificacion": "Continuo",
      "responsable": "PMO Calidad",
      "probabilidad": "Media",
      "exposicion": 0.4,
      "plan_accion": "Solicitar a ANI clarificación formal sobre metodología de medición de disponibilidad para los PAN",
      "categoria": "Contractual",
      "origen_decision": "N/A",
      "descripcion": "Ambigüedad medición disponibilidad PAN 100% (KPI inalcanzable)",
      "estrategia": "MITIGAR - Consulta Interventoría criterios medición"
    },
    {
      "items_wbs": [
        "1.1.100",
        "2.1.100"
      ],
      "fuente": "A.2 Análisis",
      "nivel_exposicion": "MEDIA",
      "probabilidad_num": 0.5,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-OPE-001",
      "hito_verificacion": "H-SAT-M44",
      "responsable": "Especialista Sistemas",
      "probabilidad": "Media",
      "exposicion": 0.4,
      "plan_accion": "Incluir pruebas de conmutación por falla (failover) en protocolos de pruebas SAT",
      "categoria": "Operacional",
      "origen_decision": "N/A",
      "descripcion": "Falla conmutación failover sistemas redundantes",
      "estrategia": "MITIGAR - Pruebas conmutación obligatorias FAT/SAT"
    },
    {
      "items_wbs": [],
      "fuente": "A.3 Análisis",
      "nivel_exposicion": "MEDIA",
      "probabilidad_num": 0.5,
      "impacto": "Alto",
      "estado": "Activo",
      "impacto_num": 0.8,
      "id": "R-CAL-001",
      "hito_verificacion": "Continuo",
      "responsable": "PMO Calidad",
      "probabilidad": "Media",
      "exposicion": 0.4,
      "plan_accion": "Implementar plan de aseguramiento de calidad estricto con inspecciones en fábrica y en sitio",
      "categoria": "Gestión",
      "origen_decision": "N/A",
      "descripcion": "Calidad materiales/mano obra no cumple estándares",
      "estrategia": "MITIGAR - Control calidad estricto, certificaciones"
    },
    {
      "items_wbs": [
        "1.1.100",
        "1.1.103",
        "1.2.100"
      ],
      "fuente": "BLOCKER-001",
      "nivel_exposicion": "CRÍTICA",
      "probabilidad_num": 0.7,
      "impacto": "Crítico",
      "estado": "Activo",
      "impacto_num": 1,
      "id": "R-PTC-001",
      "hito_verificacion": "H-PTC Nativo (FRA 49 CFR 236)-DEF-M6",
      "responsable": "Gerencia Técnica + ANI",
      "probabilidad": "Alta",
      "exposicion": 0.7,
      "plan_accion": "**ACCIÓN HOY:** Confirmar arquitectura PTC Nativo LFC. Validar ahorro de $50B COP en CAPEX.",
      "categoria": "Técnico",
      "origen_decision": "N/A",
      "descripcion": "Indefinición técnica de arquitectura PTC Nativo (Soberanía)",
      "estrategia": "EVITAR - Saneamiento Recursivo Completado"
    },
    {
      "items_wbs": [
        "1.1.106",
        "4.1.100"
      ],
      "fuente": "BLOCKER-002",
      "nivel_exposicion": "CRÍTICA",
      "probabilidad_num": 0.7,
      "impacto": "Crítico",
      "estado": "Activo",
      "impacto_num": 1,
      "id": "R-FENOCO-001",
      "hito_verificacion": "H-FENOCO-M6",
      "responsable": "PMO + FENOCO",
      "probabilidad": "Alta",
      "exposicion": 0.7,
      "plan_accion": "**ACCIÓN HOY:** Validar protocolo Stop & Switch operativo con FENOCO en interfaz Chiriguaná (BCD §6 + AT1 Tabla 17).",
      "categoria": "Técnico",
      "origen_decision": "N/A",
      "descripcion": "Interoperabilidad con sistemas legacy de FENOCO en interfaz operativa (Stop & Switch Chiriguaná)",
      "estrategia": "MITIGAR - Gateway de Abstracción de Protocolos"
    },
    {
      "items_wbs": [
        "3.2.100"
      ],
      "fuente": "BLOCKER-003",
      "nivel_exposicion": "BAJA",
      "probabilidad_num": 0.5,
      "impacto": "Medio",
      "estado": "Activo",
      "impacto_num": 0.5,
      "id": "R-PAN-001",
      "hito_verificacion": "HG-PAN-04-M10",
      "responsable": "PMO + Seguridad Vial",
      "probabilidad": "Media",
      "exposicion": 0.25,
      "plan_accion": "**ACCIÓN HOY:** Confirmar diseño modular de PANs. Validar asignación de contingencia $489M en presupuesto",
      "categoria": "Contractual",
      "origen_decision": "N/A",
      "descripcion": "Cantidades PAN NO confirmadas (regularización en curso) - Variación ±10%",
      "estrategia": "ACEPTAR - Diseño modular ±10%, contingencia $489M"
    },
    {
      "items_wbs": [
        "6.1.100"
      ],
      "fuente": "BLOCKER-004",
      "nivel_exposicion": "BAJA",
      "probabilidad_num": 0.5,
      "impacto": "Medio",
      "estado": "Activo",
      "impacto_num": 0.5,
      "id": "R-MR-001",
      "hito_verificacion": "H-MR-M5",
      "responsable": "PMO + Gerencia Operaciones",
      "probabilidad": "Media",
      "exposicion": 0.25,
      "plan_accion": "**ACCIÓN HOY:** Enviar oficio a ANI solicitando cronograma detallado de entrega. Desarrollar 3 escenarios de planificación",
      "categoria": "Gestión",
      "origen_decision": "N/A",
      "descripcion": "Cronograma MR indefinido (15 locomotoras) - Secuencia pruebas NO definida",
      "estrategia": "MITIGAR - Plan adaptable, certificación en banco si no llega"
    },
    {
      "items_wbs": [
        "2.3.100"
      ],
      "fuente": "WBS / Análisis",
      "nivel_exposicion": "BAJA",
      "probabilidad_num": 0.5,
      "impacto": "Medio",
      "estado": "Activo",
      "impacto_num": 0.5,
      "id": "R-FIBRA-006",
      "hito_verificacion": "**H-FIBRA-005**",
      "responsable": "PMO",
      "probabilidad": "20%",
      "exposicion": 0.25,
      "plan_accion": "Monitorear costo final de fibra para confirmar ahorro proyectado. Validar en H-FIBRA-005",
      "categoria": "Económico",
      "origen_decision": "**DT-FIBRA-001**",
      "descripcion": "Ahorro CAPEX no realizado si cajas cada 1000m fallan",
      "estrategia": "Aceptar: Beneficio supera riesgo"
    },
    {
      "id": "R-INT-V1-001",
      "categoria": "Contractual",
      "descripcion": "Aprobación criterios de diseño V1 por Interventoría (Apéndice Técnico 1, Tabla 17). Las cifras de la línea base son estimadas hasta la no-objeción. El cierre depende de esta aprobación.",
      "nivel_exposicion": "CRÍTICA",
      "probabilidad": "Alta",
      "probabilidad_num": 0.7,
      "impacto": "Crítico",
      "impacto_num": 0.9,
      "exposicion": 0.63,
      "estrategia": "Mitigar: paquete de criterios V1 entregado, seguimiento semanal con Interventoría",
      "plan_accion": "Entregar paquete técnico V1 completo (BCD v001 + DTs + matriz de cumplimiento AT1 Tabla 17) y agendar reuniones quincenales hasta obtener no-objeción formal",
      "responsable": "Director Técnico UF2",
      "hito_verificacion": "No-objeción Interventoría AT1 Tabla 17",
      "items_wbs": [],
      "fuente": "Contrato APP No. 001 de 2025 / AT1 Tabla 17",
      "origen_decision": "N/A",
      "estado": "Activo"
    },
    {
      "id": "R-ARDANUY-FO-001",
      "categoria": "Financiero",
      "descripcion": "Gap obra civil de fibra óptica: LFC estima $52.219M COP, Ardanuy v1 estima $122.894M COP. Diferencia de $70.675M COP (~$16M USD subestimado). Si Ardanuy cotiza correctamente, ejecución queda corta.",
      "nivel_exposicion": "ALTA",
      "probabilidad": "Alta",
      "probabilidad_num": 0.7,
      "impacto": "Alto",
      "impacto_num": 0.8,
      "exposicion": 0.56,
      "estrategia": "Mitigar: reasignación interna desde Cap 4.3 PaN básicos (fuera del alcance BCD §8.2) + Cap 6 OBU + Cap 5 CCO software",
      "plan_accion": "Ejecutar DT-COMS-2026-008: subir Cap 2.3 obra civil FO + crear capítulo Diseño Fase III, compensando con bajadas en Cap 4.3, 5 y 6. Total convergente sin tocar techo.",
      "responsable": "Ing. Comunicaciones + Director Técnico UF2",
      "hito_verificacion": "DT-COMS-2026-008 emitida y aplicada al WBS",
      "items_wbs": [
        "2.3.100",
        "2.3.101",
        "2.3.102"
      ],
      "fuente": "Validación cruzada Ardanuy LFC-U2-CTSC-ED-QTO-CO-0001 vs WBS LFC v14.7",
      "origen_decision": "Bloque D roadmap.md",
      "estado": "Activo"
    },
    {
      "id": "R-RFQ-001",
      "categoria": "Comercial",
      "descripcion": "8 ítems pendientes de cotización formal: 4 en ratificación contra ADIF (ENCE, desvíos motorizados, control remoto N+1, señales LED) + 4 sin ADIF en RFQ urgente (F.O. 48h G.652.D, contador de ejes, armario PTC SIL-3, UPS).",
      "nivel_exposicion": "MEDIA",
      "probabilidad": "Media",
      "probabilidad_num": 0.5,
      "impacto": "Medio",
      "impacto_num": 0.6,
      "exposicion": 0.3,
      "estrategia": "Mitigar: línea base ADIF v1 aplicada (DT-COMS-2026-007) con buffer +12-15% por trocha 914mm + logística + MO local",
      "plan_accion": "Lanzar RFQ formal a proveedores priorizados: Hima Colombia, Vossloh, Furukawa, Frauscher, Hima HiMax, Eaton/APC. Plazo: 30 días desde no-objeción Interventoría.",
      "responsable": "Compras / Integradora (ART, Hitachi)",
      "hito_verificacion": "RFQ recibidas y consolidadas en precios_Adif_COMPLETO.md §6",
      "items_wbs": [
        "1.3.100",
        "1.4.100",
        "1.4.101",
        "4.1.101",
        "2.3.100",
        "2.1.116"
      ],
      "fuente": "DT-COMS-2026-007 §3.5 + precios_Adif_COMPLETO.md §4",
      "origen_decision": "DT-COMS-2026-007",
      "estado": "Activo"
    },
    {
      "id": "R-TRM-001",
      "categoria": "Financiero",
      "descripcion": "Exposición cambiaria: TRM Risk 4.400 COP/USD incorpora margen ~+21% vs TRM real spot 3.637. Si la TRM se mantiene cerca del spot durante ejecución, el equivalente USD del CAPEX sube de $59,1M a $71,5M (+21%).",
      "nivel_exposicion": "MEDIA",
      "probabilidad": "Media",
      "probabilidad_num": 0.5,
      "impacto": "Alto",
      "impacto_num": 0.7,
      "exposicion": 0.35,
      "estrategia": "Transferir: cobertura cambiaria forward sobre componente de suministro importado (~60% del CAPEX)",
      "plan_accion": "Evaluar instrumento de cobertura (forward / collar) con tesorería Grupo Ortiz para componente USD del WBS. Revisar trimestralmente.",
      "responsable": "Tesorería Grupo Ortiz + Director Técnico UF2",
      "hito_verificacion": "Política de cobertura cambiaria aprobada",
      "items_wbs": [],
      "fuente": "lfc-terminology.js FINANCIAL.TRM + lectura spot Banco República",
      "origen_decision": "N/A",
      "estado": "Activo"
    },
    {
      "id": "R-ARDANUY-PERF-001",
      "categoria": "Contractual / Cronograma",
      "descripcion": "Incumplimiento de obligación de resultado por Ardanuy (TDR §2.12). Día 98 de 270. Hito 1 (DBCD) reformulado internamente por el EPC; Hito 2 (60%) radicado el 27-abr sin incorporar los criterios aprobados el 1-may. Cero reuniones técnicas entre Hitos 1 y 2. Patrón: documentación reactiva, devolución de preguntas de alcance que el contrato ya delimita, sin integración multidisciplinar con UF1. Riesgo de NO entregar la ingeniería a tiempo (Hito 4 = 5-jul-2026 + 90 días no-objeción).",
      "nivel_exposicion": "CRÍTICA",
      "probabilidad": "Alta",
      "probabilidad_num": 0.8,
      "impacto": "Crítico",
      "impacto_num": 0.9,
      "exposicion": 0.72,
      "estrategia": "Mitigar: reencauzar modelo de seguimiento. Comité técnico bisemanal + pre-radicación 15 días + carpeta de evidencias por hito (TDR §2.12 ya lo establece, hoy no se evidencia)",
      "plan_accion": "Reunión convocada 5 o 7 de mayo de 2026 con Ardanuy y Oscar (comunicación 00013-2026). Único punto en agenda: que Ardanuy presente plan operativo escrito sobre integración multidisciplinar, coordinación interna entre disciplinas, evidencia de lectura UF1+UF2, y mecanismo de pre-radicación 15 días antes de cada hito. Si no hay compromiso escrito post-reunión, escalar al Comité Directivo del Consorcio antes del 15-may-2026.",
      "responsable": "Director Técnico UF2 + Comité Directivo Consorcio",
      "hito_verificacion": "Acta firmada Ardanuy con plan operativo + 1ra pre-radicación Hito 3 cumplida 15 días antes",
      "items_wbs": [],
      "fuente": "Comunicación 00013-2026 (4-may-2026) + TDR Ardanuy §2.12 + Contrato APP No. 001 de 2025",
      "origen_decision": "Comunicación 00013-2026",
      "estado": "Activo"
    }
  ],
  "estadisticas": {
    "exposicion_critica": 5,
    "exposicion_alta": 3,
    "exposicion_media": 10,
    "exposicion_baja": 4,
    "por_estrategia": {
      "aceptar": 0,
      "asumir": 0,
      "transferir": 0,
      "evitar": 0,
      "mitigar": 0
    }
  },
  "proyecto": "APP La Dorada-Chiriguaná",
  "riesgos_vinculados": 14,
  "total_riesgos": 22
};
