window.wbsDataPresupuestal = [
    {
        "item": "1.1.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Servidores CTC principales",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 180000000,
        "total": 360000000,
        "vu_usd": 40909,
        "total_usd": 81818,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Servidores CTC respaldo",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 180000000,
        "total": 360000000,
        "vu_usd": 40909,
        "total_usd": 81818,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Workstations operadores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "8",
        "vu": 45000000,
        "total": 360000000,
        "vu_usd": 10227,
        "total_usd": 81818,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.103",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Software CTC virtual + Autorizaciones PTC (Interoperabilidad Procedimental)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 11000000000,
        "total": 11000000000,
        "vu_usd": 2500000,
        "total_usd": 2500000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.104",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Base de datos centralizada",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 200000000,
        "total": 200000000,
        "vu_usd": 45455,
        "total_usd": 45455,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.105",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Sistema redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 300000000,
        "total": 300000000,
        "vu_usd": 68182,
        "total_usd": 68182,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.1.106",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.1",
        "descripcion": "Interfaces comunicación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 34091,
        "total_usd": 34091,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Computadora PTC embarcada",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 120000000,
        "total": 1800000000,
        "vu_usd": 27273,
        "total_usd": 409091,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Display maquinista",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 80000000,
        "total": 1200000000,
        "vu_usd": 18182,
        "total_usd": 272727,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Sensores velocidad",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 25000000,
        "total": 375000000,
        "vu_usd": 5682,
        "total_usd": 85227,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.103",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Sistema GPS",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 35000000,
        "total": 525000000,
        "vu_usd": 7955,
        "total_usd": 119318,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.104",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Software PTC",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 100000000,
        "total": 1500000000,
        "vu_usd": 22727,
        "total_usd": 340909,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.105",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Interfaces frenos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 30000000,
        "total": 450000000,
        "vu_usd": 6818,
        "total_usd": 102273,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.2.106",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.2",
        "descripcion": "Sistema redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 50000000,
        "total": 750000000,
        "vu_usd": 11364,
        "total_usd": 170455,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE Zapatosa (DT-COMS-2026-007: ADIF CAC020 €356,780 + ajustes trocha 914+log−MO ≈ $2,000M COP)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 2000000000,
        "total": 2000000000,
        "vu_usd": 454545,
        "total_usd": 454545,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE García Cadena (DT-COMS-2026-007)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 2000000000,
        "total": 2000000000,
        "vu_usd": 454545,
        "total_usd": 454545,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE Barrancabermeja (Puerto) (DT-COMS-2026-007)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 2000000000,
        "total": 2000000000,
        "vu_usd": 454545,
        "total_usd": 454545,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.103",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE Puerto Berrío-Grecia (DT-COMS-2026-007)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 2000000000,
        "total": 2000000000,
        "vu_usd": 454545,
        "total_usd": 454545,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.104",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Controlador ENCE La Dorada-México (DT-COMS-2026-007)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 2000000000,
        "total": 2000000000,
        "vu_usd": 454545,
        "total_usd": 454545,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.105",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Sistema redundancia ENCE",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 400000000,
        "total": 400000000,
        "vu_usd": 90909,
        "total_usd": 90909,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.3.106",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.3",
        "descripcion": "Interfaces CTC-ENCE",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "5",
        "vu": 60000000,
        "total": 300000000,
        "vu_usd": 13636,
        "total_usd": 68182,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.4.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.4",
        "descripcion": "Desvíos motorizados CTC (DT-COMS-2026-007: ADIF VEA010 €114,320 + ajustes trocha 914+log−MO ≈ $640M COP)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "25",
        "vu": 640000000,
        "total": 16000000000,
        "vu_usd": 145455,
        "total_usd": 3636364,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.4.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.4",
        "descripcion": "Sistemas control remoto + redundancia N+1",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "25",
        "vu": 134577000,
        "total": 3364425000,
        "vu_usd": 30586,
        "total_usd": 764642,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.4.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.4",
        "descripcion": "Interfaces CTC/ENCE",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "25",
        "vu": 67288000,
        "total": 1682200000,
        "vu_usd": 15293,
        "total_usd": 382318,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.5.100",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.5",
        "descripcion": "Desvíos manuales autotalonables (con comprobador integrado)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "120",
        "vu": 134577000,
        "total": 16149240000,
        "vu_usd": 30586,
        "total_usd": 3670282,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.5.101",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.5",
        "descripcion": "Señalización semafórica estaciones ENCE (5 estaciones × 6 señales/estación promedio)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 51920000,
        "total": 1557600000,
        "vu_usd": 11800,
        "total_usd": 354000,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "1.5.102",
        "nivel": 3,
        "capitulo": "1",
        "sistema": "1.5",
        "descripcion": "Herramientas operación (kit completo certificado)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "120",
        "vu": 13458000,
        "total": 1614960000,
        "vu_usd": 3059,
        "total_usd": 367036,
        "modificable": true,
        "categoria": "control",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.100",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Torres autosoportadas",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 180000000,
        "total": 6660000000,
        "vu_usd": 40909,
        "total_usd": 1513636,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.101",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Estaciones base TETRA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 65000000,
        "total": 2405000000,
        "vu_usd": 14773,
        "total_usd": 546591,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.102",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Antenas TETRA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 12000000,
        "total": 444000000,
        "vu_usd": 2727,
        "total_usd": 100909,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.103",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Radios embarcados (30 unidades)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 35000000,
        "total": 1050000000,
        "vu_usd": 7955,
        "total_usd": 238636,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.104",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Radios portátiles",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "80",
        "vu": 6000000,
        "total": 480000000,
        "vu_usd": 1364,
        "total_usd": 109091,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.105",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Sistema control centralizado",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 120000000,
        "total": 120000000,
        "vu_usd": 27273,
        "total_usd": 27273,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.106",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Casetas técnicas",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 65000000,
        "total": 2405000000,
        "vu_usd": 14773,
        "total_usd": 546591,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.107",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Cimentaciones",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 25000000,
        "total": 925000000,
        "vu_usd": 5682,
        "total_usd": 210227,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.108",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Cerramiento perimetral",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 30000000,
        "total": 1110000000,
        "vu_usd": 6818,
        "total_usd": 252273,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.109",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Vías de acceso",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 25000000,
        "total": 925000000,
        "vu_usd": 5682,
        "total_usd": 210227,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.110",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Sistemas de seguridad",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 20000000,
        "total": 740000000,
        "vu_usd": 4545,
        "total_usd": 168182,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.111",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Montaje e instalación",
        "tipo": "OBRA",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 15000000,
        "total": 555000000,
        "vu_usd": 3409,
        "total_usd": 126136,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.112",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Configuración red",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 200000000,
        "total": 200000000,
        "vu_usd": 45455,
        "total_usd": 45455,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.113",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Pruebas cobertura",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 34091,
        "total_usd": 34091,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.114",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Capacitación",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 22727,
        "total_usd": 22727,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.115",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 1774000000,
        "total": 1774000000,
        "vu_usd": 403182,
        "total_usd": 403182,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.1.116",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.1",
        "descripcion": "Bancos baterías LiFePO4 24h autonomía sitios remotos TETRA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 50000000,
        "total": 1850000000,
        "vu_usd": 11364,
        "total_usd": 420455,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.100",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Estaciones base Red Vital IP / TETRA (Soberanía SICC v7.0)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 45000000,
        "total": 1665000000,
        "vu_usd": 10227,
        "total_usd": 378409,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.101",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Antenas Red Vital IP / TETRA (Broadband)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 8000000,
        "total": 296000000,
        "vu_usd": 1818,
        "total_usd": 67273,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.102",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Radios embarcados Red Vital IP / TETRA (ZR-Optics Compatible)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 25000000,
        "total": 750000000,
        "vu_usd": 5682,
        "total_usd": 170455,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.103",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Sistema control Red Vital IP / TETRA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 18182,
        "total_usd": 18182,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.104",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Interfaces TETRA-Red Vital IP / TETRA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "37",
        "vu": 5000000,
        "total": 185000000,
        "vu_usd": 1136,
        "total_usd": 42045,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.105",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Sistema redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 34091,
        "total_usd": 34091,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.106",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Configuración dual",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 22727,
        "total_usd": 22727,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.107",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Pruebas integración",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 18182,
        "total_usd": 18182,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.2.108",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.2",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 312000000,
        "total": 312000000,
        "vu_usd": 70909,
        "total_usd": 70909,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.100",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Cable fibra óptica monomodo 48 hilos G.652.D OSP (BCD §6.1.1 — solución homogénea 526km + 10% gasa técnica)",
        "tipo": "SUMINISTRO",
        "unidad": "KM",
        "cantidad": "579",
        "vu": 9811013,
        "total": 5680576527,
        "vu_usd": 2230,
        "total_usd": 1291040,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.101",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Mano de obra instalación (Tendido 526km + 10% Gasa Técnica)",
        "tipo": "OBRA",
        "unidad": "KM",
        "cantidad": "579",
        "vu": 90188987,
        "total": 52219423473,
        "vu_usd": 20497,
        "total_usd": 11868051,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.102",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Tritubo 40mm",
        "tipo": "SUMINISTRO",
        "unidad": "ROLLO",
        "cantidad": "1448",
        "vu": 15845,
        "total": 22943560,
        "vu_usd": 4,
        "total_usd": 5214,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.103",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Cajas empalme 80x80",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1930",
        "vu": 1350000,
        "total": 2605500000,
        "vu_usd": 307,
        "total_usd": 592159,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.104",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Uniones rápidas",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "5790",
        "vu": 35000,
        "total": 202650000,
        "vu_usd": 8,
        "total_usd": 46057,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.105",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Fusionadoras",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 50000000,
        "total": 100000000,
        "vu_usd": 11364,
        "total_usd": 22727,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.106",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "OTDR triwavelength (1310/1550/1625 nm)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 90000000,
        "total": 180000000,
        "vu_usd": 20455,
        "total_usd": 40909,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.107",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Muflas fusionado",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "6800",
        "vu": 25000,
        "total": 170000000,
        "vu_usd": 6,
        "total_usd": 38636,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.108",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Insumos fusionado",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "6200",
        "vu": 15000,
        "total": 93000000,
        "vu_usd": 3,
        "total_usd": 21136,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.3.109",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Repuestos Estratégicos (Stock 3% Corredor)",
        "tipo": "SUMINISTRO",
        "unidad": "KM",
        "cantidad": "16",
        "vu": 8000000,
        "total": 128000000,
        "vu_usd": 1818,
        "total_usd": 29091,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "2.4.100",
        "nivel": 3,
        "capitulo": "2",
        "sistema": "2.4",
        "descripcion": "Habilitación Satelital Transitoria (Punto 42) — 5 terminales LEO + 12 meses suscripción (DT-SICC-2026-042, cadena 9.12→25.4)",
        "tipo": "SUMINISTRO",
        "unidad": "GLB",
        "cantidad": "1",
        "vu": 1200000000,
        "total": 1200000000,
        "vu_usd": 272727,
        "total_usd": 272727,
        "modificable": true,
        "categoria": "telecomunicaciones",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.100",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Cámaras PAN PTZ 4MP (73 unidades - cobertura completa)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "73",
        "vu": 30000000,
        "total": 2190000000,
        "vu_usd": 6818,
        "total_usd": 497727,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.101",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Cámaras talleres (12 unidades)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "12",
        "vu": 6000000,
        "total": 72000000,
        "vu_usd": 1364,
        "total_usd": 16364,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.102",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Cámaras CCO (8 unidades)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "8",
        "vu": 10000000,
        "total": 80000000,
        "vu_usd": 2273,
        "total_usd": 18182,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.103",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Cámaras estaciones (5 unidades)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "5",
        "vu": 7000000,
        "total": 35000000,
        "vu_usd": 1591,
        "total_usd": 7955,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.104",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Sistema grabación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 34091,
        "total_usd": 34091,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.105",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Servidores almacenamiento",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 80000000,
        "total": 160000000,
        "vu_usd": 18182,
        "total_usd": 36364,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.106",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Software análisis",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 120000000,
        "total": 120000000,
        "vu_usd": 27273,
        "total_usd": 27273,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.107",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Monitores CCO",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "8",
        "vu": 15000000,
        "total": 120000000,
        "vu_usd": 3409,
        "total_usd": 27273,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.108",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Instalación y configuración",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "73",
        "vu": 2000000,
        "total": 146000000,
        "vu_usd": 455,
        "total_usd": 33182,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.1.109",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.1",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 307300000,
        "total": 307300000,
        "vu_usd": 69841,
        "total_usd": 69841,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.100",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Lectores RFID control accesos (ISO 14443, IP65/IK10)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "100",
        "vu": 3000000,
        "total": 300000000,
        "vu_usd": 682,
        "total_usd": 68182,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.101",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Tarjetas RFID",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1000",
        "vu": 25000,
        "total": 25000000,
        "vu_usd": 6,
        "total_usd": 5682,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.102",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Sistema biométrico",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "5",
        "vu": 50000000,
        "total": 250000000,
        "vu_usd": 11364,
        "total_usd": 56818,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.103",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Software control accesos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 18182,
        "total_usd": 18182,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.104",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Cerraduras electrónicas",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "50",
        "vu": 8000000,
        "total": 400000000,
        "vu_usd": 1818,
        "total_usd": 90909,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.105",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Intercomunicadores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "20",
        "vu": 15000000,
        "total": 300000000,
        "vu_usd": 3409,
        "total_usd": 68182,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.106",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Instalación y configuración",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 22727,
        "total_usd": 22727,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.2.107",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.2",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 145500000,
        "total": 145500000,
        "vu_usd": 33068,
        "total_usd": 33068,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.100",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Detectores humo",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "200",
        "vu": 150000,
        "total": 30000000,
        "vu_usd": 34,
        "total_usd": 6818,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.101",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Detectores temperatura",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "150",
        "vu": 200000,
        "total": 30000000,
        "vu_usd": 45,
        "total_usd": 6818,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.102",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Sistema aspersores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "50",
        "vu": 800000,
        "total": 40000000,
        "vu_usd": 182,
        "total_usd": 9091,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.103",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Extintores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "100",
        "vu": 500000,
        "total": 50000000,
        "vu_usd": 114,
        "total_usd": 11364,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.104",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Sistema alarma",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 120000000,
        "total": 120000000,
        "vu_usd": 27273,
        "total_usd": 27273,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.105",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Botones emergencia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 500000,
        "total": 15000000,
        "vu_usd": 114,
        "total_usd": 3409,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.106",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Instalación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 18182,
        "total_usd": 18182,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "3.3.107",
        "nivel": 3,
        "capitulo": "3",
        "sistema": "3.3",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 36500000,
        "total": 36500000,
        "vu_usd": 8295,
        "total_usd": 8295,
        "modificable": true,
        "categoria": "its_seguridad",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.100",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Sistemas barreras automáticas SIL-3 vital (FRA Part 236 Subpart I)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 180000000,
        "total": 1620000000,
        "vu_usd": 40909,
        "total_usd": 368182,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.101",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Senalización LED (Res. 20243040045005)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 80000000,
        "total": 720000000,
        "vu_usd": 18182,
        "total_usd": 163636,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.102",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Sistemas detección vehículos SIL-3 vital (FRA Part 236 Subpart I)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 360000000,
        "total": 3240000000,
        "vu_usd": 81818,
        "total_usd": 736364,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.103",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Sistemas comunicación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 60000000,
        "total": 540000000,
        "vu_usd": 13636,
        "total_usd": 122727,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.104",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Sistemas emergencia SIL-3 vital (FRA Part 236 Subpart I)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 40000000,
        "total": 360000000,
        "vu_usd": 9091,
        "total_usd": 81818,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.105",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Instalación y configuración",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "9",
        "vu": 200000000,
        "total": 1800000000,
        "vu_usd": 45455,
        "total_usd": 409091,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.1.106",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.1",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 828000000,
        "total": 828000000,
        "vu_usd": 188182,
        "total_usd": 188182,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.100",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Señales Luminosas y Acústicas (SLA) — PaN Tipo B (BCD §8.2.1, NTC 4741:1999). VU pendiente RFQ COL.",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 120000000,
        "total": 1800000000,
        "vu_usd": 27273,
        "total_usd": 409091,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.101",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Senalización basica (Res. 20243040045005)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 50000000,
        "total": 750000000,
        "vu_usd": 11364,
        "total_usd": 170455,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.102",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Sistemas detección",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 80000000,
        "total": 1200000000,
        "vu_usd": 18182,
        "total_usd": 272727,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.103",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Sistemas comunicación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 40000000,
        "total": 600000000,
        "vu_usd": 9091,
        "total_usd": 136364,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.104",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Instalación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 60000000,
        "total": 900000000,
        "vu_usd": 13636,
        "total_usd": 204545,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.2.105",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.2",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 525000000,
        "total": 525000000,
        "vu_usd": 119318,
        "total_usd": 119318,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.3.100",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.3",
        "descripcion": "Senalización basica (Manual 2024 / Res. 20243040045005)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "122",
        "vu": 25000000,
        "total": 3050000000,
        "vu_usd": 5682,
        "total_usd": 693182,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.3.101",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.3",
        "descripcion": "Sistemas comunicación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "0",
        "vu": 20000000,
        "total": 0,
        "vu_usd": 4545,
        "total_usd": 0,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.3.102",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.3",
        "descripcion": "Instalación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "0",
        "vu": 30000000,
        "total": 0,
        "vu_usd": 6818,
        "total_usd": 0,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "4.3.103",
        "nivel": 3,
        "capitulo": "4",
        "sistema": "4.3",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 305000000,
        "total": 305000000,
        "vu_usd": 69318,
        "total_usd": 69318,
        "modificable": true,
        "categoria": "pasos_nivel",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.100",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Construcción edificio",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 2500000000,
        "total": 2500000000,
        "vu_usd": 568182,
        "total_usd": 568182,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.101",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sala de control",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 800000000,
        "total": 800000000,
        "vu_usd": 181818,
        "total_usd": 181818,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.102",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sistemas HVAC",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 300000000,
        "total": 300000000,
        "vu_usd": 68182,
        "total_usd": 68182,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.103",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sistemas eléctricos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 400000000,
        "total": 400000000,
        "vu_usd": 90909,
        "total_usd": 90909,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.104",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sistemas seguridad",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 200000000,
        "total": 200000000,
        "vu_usd": 45455,
        "total_usd": 45455,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.1.105",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.1",
        "descripcion": "Sistemas comunicaciones",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 34091,
        "total_usd": 34091,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.100",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Consolas operadores",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "8",
        "vu": 120000000,
        "total": 960000000,
        "vu_usd": 27273,
        "total_usd": 218182,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.101",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Pantallas de video",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "16",
        "vu": 25000000,
        "total": 400000000,
        "vu_usd": 5682,
        "total_usd": 90909,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.102",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Sistema audio",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 80000000,
        "total": 80000000,
        "vu_usd": 18182,
        "total_usd": 18182,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.103",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Sistema iluminación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 60000000,
        "total": 60000000,
        "vu_usd": 13636,
        "total_usd": 13636,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.2.104",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.2",
        "descripcion": "Muebles y accesorios",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 22727,
        "total_usd": 22727,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.100",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Servidores SCADA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 400000000,
        "total": 800000000,
        "vu_usd": 90909,
        "total_usd": 181818,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.101",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Software SCADA",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 5000000000,
        "total": 5000000000,
        "vu_usd": 1136364,
        "total_usd": 1136364,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.102",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Base de datos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 150000000,
        "total": 150000000,
        "vu_usd": 34091,
        "total_usd": 34091,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.103",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Interfaces comunicación",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 4112000000,
        "total": 4112000000,
        "vu_usd": 934545,
        "total_usd": 934545,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.104",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Sistema redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 300000000,
        "total": 300000000,
        "vu_usd": 68182,
        "total_usd": 68182,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "5.3.105",
        "nivel": 3,
        "capitulo": "5",
        "sistema": "5.3",
        "descripcion": "Configuración",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 100000000,
        "total": 100000000,
        "vu_usd": 22727,
        "total_usd": 22727,
        "modificable": true,
        "categoria": "cco",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.100",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Sistemas PTC embarcados",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 400000000,
        "total": 6000000000,
        "vu_usd": 90909,
        "total_usd": 1363636,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.101",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Radios TETRA embarcados",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 35000000,
        "total": 1050000000,
        "vu_usd": 7955,
        "total_usd": 238636,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.102",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Radios Red Vital IP / TETRA embarcados",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "30",
        "vu": 25000000,
        "total": 750000000,
        "vu_usd": 5682,
        "total_usd": 170455,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.103",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Sistemas GPS",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 35000000,
        "total": 525000000,
        "vu_usd": 7955,
        "total_usd": 119318,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.104",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Sistemas redundancia",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 80000000,
        "total": 1200000000,
        "vu_usd": 18182,
        "total_usd": 272727,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.105",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Instalación y configuración",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 100000000,
        "total": 1500000000,
        "vu_usd": 22727,
        "total_usd": 340909,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.1.106",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.1",
        "descripcion": "Repuestos (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 1102500000,
        "total": 1102500000,
        "vu_usd": 250568,
        "total_usd": 250568,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.2.100",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.2",
        "descripcion": "Dispositivos EOT completos",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 25000000,
        "total": 375000000,
        "vu_usd": 5682,
        "total_usd": 85227,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.2.101",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.2",
        "descripcion": "Repuestos EOT (10%)",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "2",
        "vu": 25000000,
        "total": 50000000,
        "vu_usd": 5682,
        "total_usd": 11364,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.2.102",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.2",
        "descripcion": "Instalación EOT",
        "tipo": "SUMINISTRO",
        "unidad": "UND",
        "cantidad": "15",
        "vu": 5000000,
        "total": 75000000,
        "vu_usd": 1136,
        "total_usd": 17045,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    },
    {
        "item": "6.2.103",
        "nivel": 3,
        "capitulo": "6",
        "sistema": "6.2",
        "descripcion": "Configuración EOT",
        "tipo": "SERVICIO",
        "unidad": "UND",
        "cantidad": "1",
        "vu": 20000000,
        "total": 20000000,
        "vu_usd": 4545,
        "total_usd": 4545,
        "modificable": true,
        "categoria": "material_rodante",
        "archivos_relacionados": [],
        "riesgos_asociados": []
    }
];